### ISSUE TITLE
Zero Activity & No Leaders?

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-project-threat-model#1]
@hblankenship Can this repo just go away?

There's no actual content, no leaders, it's just empty/blank.

**Comment by hblankenship** [comment]
Well, it has leaders. I will send them a quick email.

**Comment by kingthorin** [comment]
Fair leaders.md does have content, but index.md and info.md are still default example content after 16mo.

**Comment by kingthorin** [comment]
Any news on this?

**Comment by hblankenship** [comment]
I had contacted the previous project owners who indicated that they would
like to continue pursuing this project. I will be contacting them again as
it has been nearly 30 days and I don't see any further traction.

Regards,

Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects

[image: email footer.png] <https://20thanniversary.owasp.org>

**Comment by avidouglen** [comment]
Rebooting this project now - starting by collating all the current information, and @swierckx and I will be building on from there.
