### ISSUE TITLE
Broken link to OWASP Threatspec

### ISSUE THREAD

**Issue by jgadsden** [OWASP/www-project-threat-model#7]
There is a tantalising link to [OWASP Threatspec](https://owasp.org/www-project-threatspec/) that is 404 on page tab_threatmodeling.md

There is the site: https://threatspec.org/
so was there the intention at some point to move this to the OWASP organisation?

Reason for asking is that I am working on the Threat Modeling section of the OWASP Developer Guide

**Comment by jgadsden** [comment]
Closing this as it is probably historical

**Comment by avidouglen** [comment]
Oops missed this before. Yes it was supposed to be an OWASP project at some point, apparently its not anymore... 
I fixed the link as per your suggestion @jgadsden , https://github.com/OWASP/www-project-threat-model/commit/f3cadd249272bb7cee2275cb220461b549715479
